export const motivationalQuotes = [
  "The best way to get started is to quit talking and begin doing.",
  "Success is not in what you have, but who you are.",
  "Doubt kills more dreams than failure ever will.",
  "Great things never come from comfort zones.",
  "Push yourself, because no one else is going to do it for you.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Little things make big days.",
  "It always seems impossible until it’s done.",
  "Don’t stop until you’re proud.",
  "Believe you can and you're halfway there.",
  "Your limitation—it’s only your imagination.",
  "Sometimes later becomes never. Do it now.",
  "Don’t wait for opportunity. Create it.",
  "Do something today that your future self will thank you for.",
  "Dream bigger. Do bigger.",
  "Work hard in silence, let success make the noise.",
  "Stay positive, work hard, make it happen.",
];
